---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Resources:
    - Homepage Documentation:
        - abbr: HP
          href: https://gethomepage.dev/latest/
    - Homepage Custom APIs:
        - abbr: HP
          href: https://gethomepage.dev/widgets/services/customapi/
#
#- Social:
#    - Reddit:
#        - abbr: RE
#          href: https://reddit.com/
#
#- Entertainment:
#    - YouTube:
#        - abbr: YT
#          href: https://youtube.com/
