---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- greeting:
    text: ADLER

- resources:
    label: Resources
    expanded: true
    cpu: true
    memory: true

- glances:
    # sudo apt-get install glances
    # /usr/bin/glances -w in systemd unit
    url: http://{{HOMEPAGE_VAR_ADDRESS}}:61208
    label: System
    cpu: false
    mem: false
    expanded: true
    target: _blank
    diskUnits: bbytes
    disk: 
      - /

- glances:
    # sudo apt-get install glances
    # /usr/bin/glances -w in systemd unit
    url: http://{{HOMEPAGE_VAR_ADDRESS}}:61208
    label: Home
    cpu: false
    mem: false
    expanded: true
    target: _blank
    diskUnits: bbytes
    disk: 
      - /home

- glances:
    # sudo apt-get install glances
    # /usr/bin/glances -w in systemd unit
    url: http://{{HOMEPAGE_VAR_ADDRESS}}:61208
    label: Media
    cpu: false
    mem: false
    expanded: true
    target: _blank
    diskUnits: bbytes
    disk: 
      - /var/media
